### ISSUE TITLE
Design: Wireframing tools

### ISSUE THREAD

**Issue by afbk** [CodingGardenCommunity/app-wiki#4]
Hi everyone. Below is a list of wireframing tools for us to decide on.
I feel like webapps might be the best solution, so as to not exclude anyone by using platform specific tools.
Add any tools that I might have missed in the comments, and we can maybe pick out a few for a vote in the end.

| Name/URL | Platform | Pricing |
|----------------|--------------------------------|--------------------|
| Adobe XD | Windows & Mac | Free to cheap |
| www.wireframe.cc | Web app | Free to cheap |
| www.uxpin.com | Web app | Pricy |
| www.fluidui.com | Web app | Kind of pricy |
| www.balsamiq.com | Windows & Mac & web app | Cheap |
| www.pidoco.com | Web app | Cheap |
| http://pencil.evolus.vn | Windows, Mac and Linux | Free & Open source |
| www.gliffy.com | Web app | Cheap |
| www.mockflow.com | Web app | Free to cheap |
| www.framebox.org | Web app | Free |
| www.hotgloo.com | Web app | Pricy |
| www.moqups.com | Web app | Free to cheap |
| https://www.figma.com/wireframe-tool/ | Web app | Free to pricy |

**Comment by joshuaferr1s** [comment]
Figma is missing.

**Comment by afbk** [comment]
Figma added to the list.

**Comment by ohmyshell** [comment]
Adobe XD is free 
EDIT: https://www.adobe.com/products/xd.html

**Comment by afbk** [comment]
> Adobe XD is free
> EDIT: https://www.adobe.com/products/xd.html

Awesome! I thought it required the CC subscription, but there's a free starter-plan as well. Updated.

**Comment by aronhoyer** [comment]
Ok, I know I'm bringing this up to developers. So inb4 blasphemy. What about [Webflow](https://webflow.com/)? Kinda design and code at the same time. Has a free plan, kinda iffy to get into, but you're left with a highly interactive prototype.

**Comment by rabbitwerks** [comment]
Issue closed - Figma was chosen as Wireframing Tech.
